[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[colors]
[colors.cursor]
text = '0xffffff'
cursor = '0x4d4d4c'
 
[colors.normal]
black ='0xffffff'
red = '0xc82829'
green ='0x718c00'
yellow ='0xeab700'
blue ='0x4271ae'
magenta = '0x8959a8'
cyan = '0x3e999f'
white = '0x4d4d4c'


  # Bright colors
[colors.bright]
black = '0x8e908c'
red = '0xf5871f'
green = '0xe0e0e0'
yellow = '0xd6d6d6'
blue = '0x969896'
magenta = '0x282a2e'
cyan = '0xa3685a'
white = '0x1d1f21'